-- Configurable Approval Workflow Engine
-- Admin builds workflows per module; each workflow can have several amount
-- bands, each with an ordered list of approval role steps. The engine resolves
-- the applicable band for a request and advances through its steps.

create table if not exists public.approval_workflows (
  id bigint generated by default as identity primary key,
  module text not null,
  request_type text not null default 'default',
  name text not null,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (module, request_type)
);

create table if not exists public.approval_workflow_bands (
  id bigint generated by default as identity primary key,
  workflow_id bigint not null references public.approval_workflows (id) on delete cascade,
  min_amount numeric(14,2),
  max_amount numeric(14,2),
  label text not null default '',
  sort_order integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.approval_workflow_steps (
  id bigint generated by default as identity primary key,
  band_id bigint not null references public.approval_workflow_bands (id) on delete cascade,
  step_no integer not null,
  role_id text not null,
  approver_user_id text,
  required boolean not null default true,
  created_at timestamptz not null default now(),
  unique (band_id, step_no)
);

-- Existing deployments: add the optional per-step assigned person column.
alter table public.approval_workflow_steps add column if not exists approver_user_id text;

-- Transaction log of every approval action, per blueprint section 22.
create table if not exists public.approvals (
  id bigint generated by default as identity primary key,
  module text not null,
  request_type text not null default 'default',
  request_id bigint not null,
  workflow_id bigint references public.approval_workflows (id),
  band_id bigint references public.approval_workflow_bands (id),
  step_no integer,
  approver_user_id text,
  approver_role_id text,
  action text not null default 'PENDING' check (action in ('PENDING', 'APPROVED', 'REJECTED', 'SENT_BACK', 'FORWARDED')),
  comments text not null default '',
  ip_address text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists approval_workflow_bands_workflow_idx on public.approval_workflow_bands (workflow_id);

-- Tracks how many approval steps a request has already completed. The engine
-- uses this to route through configurable workflows instead of hard-coding
-- statuses. Kept in sync with the generic `approvals` log table.
alter table public.purchase_requests add column if not exists approval_step integer not null default 0;
alter table public.car_requests add column if not exists approval_step integer not null default 0;
alter table public.maintenance_requests add column if not exists approval_step integer not null default 0;
create index if not exists approval_workflow_steps_band_idx on public.approval_workflow_steps (band_id);
create index if not exists approvals_request_idx on public.approvals (module, request_type, request_id);

alter table public.approval_workflows enable row level security;
alter table public.approval_workflow_bands enable row level security;
alter table public.approval_workflow_steps enable row level security;
alter table public.approvals enable row level security;

drop policy if exists "Allow all on approval_workflows" on public.approval_workflows;
drop policy if exists "Allow all on approval_workflow_bands" on public.approval_workflow_bands;
drop policy if exists "Allow all on approval_workflow_steps" on public.approval_workflow_steps;
drop policy if exists "Allow all on approvals" on public.approvals;
create policy "Allow all on approval_workflows" on public.approval_workflows for all using (true) with check (true);
create policy "Allow all on approval_workflow_bands" on public.approval_workflow_bands for all using (true) with check (true);
create policy "Allow all on approval_workflow_steps" on public.approval_workflow_steps for all using (true) with check (true);
create policy "Allow all on approvals" on public.approvals for all using (true) with check (true);

-- Seed a default two-band Local Purchase workflow (<=10000 and >10000),
-- matching the blueprint's worked example. Admin can edit freely.
insert into public.approval_workflows (module, request_type, name, status)
values ('purchase', 'local', 'Local Purchase', 'active')
on conflict (module, request_type) do nothing;

do $$
declare wf bigint; band_a bigint; band_b bigint;
begin
  select id into wf from public.approval_workflows
  where module = 'purchase' and request_type = 'local' limit 1;

  if (select count(*) from public.approval_workflow_bands where workflow_id = wf) = 0 then
    insert into public.approval_workflow_bands (workflow_id, min_amount, max_amount, sort_order)
    values (wf, null, 10000.00, 1);
    insert into public.approval_workflow_bands (workflow_id, min_amount, max_amount, sort_order)
    values (wf, 10000.01, null, 2);
  end if;

  select id into band_a from public.approval_workflow_bands where workflow_id = wf and max_amount = 10000.00 limit 1;
  select id into band_b from public.approval_workflow_bands where workflow_id = wf and max_amount is null limit 1;

  if (select count(*) from public.approval_workflow_steps where band_id = band_a) = 0 then
    insert into public.approval_workflow_steps (band_id, step_no, role_id) values
      (band_a, 1, 'head'), (band_a, 2, 'purchase_officer');
  end if;

  if (select count(*) from public.approval_workflow_steps where band_id = band_b) = 0 then
    insert into public.approval_workflow_steps (band_id, step_no, role_id) values
      (band_b, 1, 'head'), (band_b, 2, 'purchase_officer'),
      (band_b, 3, 'principal'), (band_b, 4, 'chairman');
  end if;
end $$;

notify pgrst, 'reload schema';
