alter table public.auditoriums
  add column if not exists approval_1_role text not null default 'head',
  add column if not exists approval_2_role text not null default 'electrician',
  add column if not exists approval_3_role text not null default 'principal';
alter table public.auditoriums add column if not exists approval_4_role text not null default 'maintenance';
alter table public.auditoriums add column if not exists is_locked boolean not null default false;
alter table public.auditoriums add column if not exists capacity integer not null default 300;
alter table public.auditoriums drop constraint if exists auditoriums_capacity_check;
alter table public.auditoriums add constraint auditoriums_capacity_check check (capacity > 0);

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  head_user_id text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_accounts (
  id text primary key,
  name text not null,
  department text not null,
  role text not null check (role in ('admin', 'sub_admin', 'admin_officer', 'purchase_officer', 'purchase_clerk', 'chairman', 'department_user', 'head', 'maintenance', 'electrician', 'principal', 'higher_authority')),
  password text not null,
  created_at timestamptz not null default now()
);

insert into public.departments (name, head_user_id) values
  ('Computer Engineering', 'hod.computer@svit.ac.in')
on conflict (name) do nothing;

insert into public.auditoriums (name) values
  ('Main Auditorium'),
  ('Seminar Auditorium')
on conflict (name) do nothing;

alter table public.user_accounts drop constraint if exists user_accounts_role_check;
alter table public.user_accounts add constraint user_accounts_role_check check (role in ('admin', 'sub_admin', 'admin_officer', 'purchase_officer', 'purchase_clerk', 'chairman', 'department_user', 'head', 'maintenance', 'electrician', 'principal', 'higher_authority'));

alter table public.requests add column if not exists requester_id text not null default 'public';
alter table public.requests add column if not exists rejection_remarks text;
alter table public.requests add column if not exists student_count integer not null default 1;
alter table public.requests drop constraint if exists requests_student_count_check;
alter table public.requests add constraint requests_student_count_check check (student_count > 0);
alter table public.requests add column if not exists end_date date not null default current_date;
alter table public.requests add column if not exists duration text not null default '1 day';
alter table public.requests add column if not exists time_slots jsonb not null default '[]'::jsonb;
alter table public.requests drop constraint if exists requests_duration_check;
alter table public.requests add constraint requests_duration_check check (duration in ('1 day', '2 days', 'multiple days'));
alter table public.requests drop constraint if exists requests_status_check;
alter table public.requests add constraint requests_status_check check (status in ('pending', 'first_approved', 'second_approved', 'third_approved', 'approved', 'rejected'));

create table if not exists public.car_requests (
  id bigint generated by default as identity primary key,
  department text not null,
  purpose text not null,
  travel_date date not null,
  passenger_count integer not null check (passenger_count > 0),
  passenger_details jsonb not null default '[]'::jsonb,
  pickup_location text not null,
  destination text not null,
  pickup_time time not null,
  return_time time,
  faculty_name text not null default '',
  requester_name text not null,
  requester_mobile text not null,
  requester_email text not null,
  remarks text not null default '',
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  rejection_remarks text,
  created_at timestamptz not null default now()
);

alter table public.car_requests add column if not exists faculty_name text not null default '';
alter table public.car_requests add column if not exists passenger_details jsonb not null default '[]'::jsonb;
alter table public.purchase_requests add column if not exists item_details jsonb not null default '[]'::jsonb;

create table if not exists public.purchase_stock (
  id bigint generated by default as identity primary key,
  category text not null default 'misc' check (category in ('stationary', 'cleaning', 'electric', 'plumbing', 'misc')),
  department text not null,
  item_name text not null,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  updated_at timestamptz not null default now(),
  unique (department, item_name)
);
alter table public.purchase_stock add column if not exists category text not null default 'misc';
alter table public.purchase_stock drop constraint if exists purchase_stock_category_check;
alter table public.purchase_stock add constraint purchase_stock_category_check check (category in ('stationary', 'cleaning', 'electric', 'plumbing', 'misc'));
alter table public.purchase_stock enable row level security;

alter table public.car_requests enable row level security;
create index if not exists car_requests_status_idx on public.car_requests (status);
create index if not exists car_requests_travel_date_idx on public.car_requests (travel_date);

notify pgrst, 'reload schema';
