create table if not exists public.role_assignments (
  id bigint generated by default as identity primary key,
  user_id text not null,
  name text not null default '',
  department text not null default '',
  role text not null check (role in ('admin', 'sub_admin', 'admin_officer', 'purchase_officer', 'purchase_clerk', 'chairman', 'department_user', 'head', 'maintenance', 'electrician', 'principal', 'higher_authority', 'work_done')),
  created_at timestamptz not null default now(),
  unique (user_id, role, department)
);

alter table public.role_assignments drop constraint if exists role_assignments_role_check;
alter table public.role_assignments add constraint role_assignments_role_check check (role in ('admin', 'sub_admin', 'admin_officer', 'purchase_officer', 'purchase_clerk', 'chairman', 'department_user', 'head', 'maintenance', 'electrician', 'principal', 'higher_authority', 'work_done'));

alter table public.role_assignments enable row level security;

drop policy if exists "public read role assignments" on public.role_assignments;
create policy "public read role assignments" on public.role_assignments
  for select using (true);

drop policy if exists "admin write role assignments" on public.role_assignments;
create policy "admin write role assignments" on public.role_assignments
  for all using (auth.jwt() ->> 'role' in ('admin', 'sub_admin')) with check (auth.jwt() ->> 'role' in ('admin', 'sub_admin'));
