alter table public.auditoriums
  add column if not exists approval_1_role text not null default 'head',
  add column if not exists approval_2_role text not null default 'electrician',
  add column if not exists approval_3_role text not null default 'principal';
alter table public.auditoriums add column if not exists approval_4_role text not null default 'maintenance';
alter table public.auditoriums add column if not exists is_locked boolean not null default false;
alter table public.auditoriums add column if not exists capacity integer not null default 300;
alter table public.auditoriums drop constraint if exists auditoriums_capacity_check;
alter table public.auditoriums add constraint auditoriums_capacity_check check (capacity > 0);

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  head_user_id text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_accounts (
  id text primary key,
  name text not null,
  department text not null,
  role text not null check (role in ('admin', 'department_user', 'head', 'maintenance', 'electrician', 'principal', 'higher_authority')),
  password text not null,
  created_at timestamptz not null default now()
);

insert into public.departments (name, head_user_id) values
  ('Computer Engineering', 'hod.computer@svit.ac.in')
on conflict (name) do nothing;

alter table public.requests add column if not exists requester_id text not null default 'public';
alter table public.requests add column if not exists rejection_remarks text;
alter table public.requests add column if not exists student_count integer not null default 1;
alter table public.requests drop constraint if exists requests_student_count_check;
alter table public.requests add constraint requests_student_count_check check (student_count > 0);
alter table public.requests add column if not exists end_date date not null default current_date;
alter table public.requests add column if not exists duration text not null default '1 day';
alter table public.requests add column if not exists time_slots jsonb not null default '[]'::jsonb;
alter table public.requests drop constraint if exists requests_duration_check;
alter table public.requests add constraint requests_duration_check check (duration in ('1 day', '2 days', 'multiple days'));
alter table public.requests drop constraint if exists requests_status_check;
alter table public.requests add constraint requests_status_check check (status in ('pending', 'first_approved', 'second_approved', 'third_approved', 'approved', 'rejected'));

notify pgrst, 'reload schema';
