-- In-app notification system (blueprint section 26) and role-module
-- permission matrix (blueprint section 12), plus a stock transaction ledger
-- (blueprint section 20).

-- ==== 26. NOTIFICATIONS ====
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id text not null,
  title text not null,
  message text not null default '',
  module text not null default '',
  reference_id text not null default '',
  link text not null default '',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_idx on public.notifications (user_id, is_read);
create index if not exists notifications_created_idx on public.notifications (created_at);

alter table public.notifications enable row level security;
drop policy if exists "Allow all on notifications" on public.notifications;
create policy "Allow all on notifications" on public.notifications for all using (true) with check (true);

-- ==== 12. ROLE-MODULE PERMISSION MATRIX ====
-- module_permissions defines which roles may access each module and the action
-- (request / approve / manage / stock / view / none). Admin edits this freely.
create table if not exists public.module_permissions (
  id bigint generated by default as identity primary key,
  module text not null,
  role text not null,
  action text not null default 'view',
  created_at timestamptz not null default now(),
  unique (module, role)
);

alter table public.module_permissions enable row level security;
drop policy if exists "Allow all on module_permissions" on public.module_permissions;
create policy "Allow all on module_permissions" on public.module_permissions for all using (true) with check (true);

insert into public.module_permissions (module, role, action) values
  ('auditorium', 'admin', 'manage'), ('auditorium', 'head', 'approve'), ('auditorium', 'department_user', 'request'), ('auditorium', 'principal', 'approve'),
  ('maintenance', 'admin', 'manage'), ('maintenance', 'head', 'approve'), ('maintenance', 'department_user', 'request'), ('maintenance', 'maintenance', 'approve'), ('maintenance', 'electrician', 'approve'), ('maintenance', 'principal', 'approve'),
  ('purchase', 'admin', 'manage'), ('purchase', 'head', 'approve'), ('purchase', 'department_user', 'request'), ('purchase', 'purchase_officer', 'approve'), ('purchase', 'purchase_clerk', 'stock'), ('purchase', 'admin_officer', 'approve'), ('purchase', 'principal', 'approve'), ('purchase', 'chairman', 'approve'),
  ('car', 'admin', 'manage'), ('car', 'head', 'approve'), ('car', 'department_user', 'request'), ('car', 'admin_officer', 'approve'), ('car', 'principal', 'approve'),
  ('inventory', 'admin', 'manage'), ('inventory', 'head', 'view'), ('inventory', 'department_user', 'entry'), ('inventory', 'purchase_clerk', 'stock'), ('inventory', 'purchase_officer', 'stock'), ('inventory', 'principal', 'view')
on conflict (module, role) do nothing;

-- ==== 20. STOCK TRANSACTIONS ====
-- Every stock movement is recorded here so current_stock can always be derived
-- from history instead of being relied on as the single source of truth.
create table if not exists public.stock_transactions (
  id bigint generated by default as identity primary key,
  item_id bigint references public.purchase_stock (id) on delete set null,
  department text not null default '',
  item_name text not null,
  category text not null default 'misc',
  transaction_type text not null check (transaction_type in ('PURCHASE', 'OPENING', 'ISSUE', 'RETURN', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT', 'DAMAGE')),
  quantity numeric(14,2) not null default 0,
  previous_stock numeric(14,2) not null default 0,
  new_stock numeric(14,2) not null default 0,
  reference_type text not null default '',
  reference_id text not null default '',
  issued_by text not null default '',
  remarks text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists stock_transactions_item_idx on public.stock_transactions (item_id);
create index if not exists stock_transactions_department_idx on public.stock_transactions (department, item_name);

alter table public.stock_transactions enable row level security;
drop policy if exists "Allow all on stock_transactions" on public.stock_transactions;
create policy "Allow all on stock_transactions" on public.stock_transactions for all using (true) with check (true);

notify pgrst, 'reload schema';
