create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  department text not null,
  program text not null,
  date date not null,
  end_date date not null default current_date,
  duration text not null default '1 day' check (duration in ('1 day', '2 days', 'multiple days')),
  start_time time,
  end_time time,
  auditorium text not null check (auditorium in ('Architecture Auditorium', 'Aeronautical Auditorium')),
  faculty_name text,
  requester_id text not null default 'public',
  status text not null default 'pending' check (status in ('pending', 'first_approved', 'second_approved', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.auditoriums (
  id bigint generated by default as identity primary key,
  name text not null unique,
  approval_1_role text not null default 'head',
  approval_2_role text not null default 'electrician',
  approval_3_role text not null default 'principal',
  is_locked boolean not null default false,
  created_at timestamptz not null default now()
);

insert into public.auditoriums (name) values
  ('Architecture Auditorium'),
  ('Aeronautical Auditorium')
on conflict (name) do nothing;

alter table public.auditoriums add column if not exists approval_1_role text not null default 'head';
alter table public.auditoriums add column if not exists approval_2_role text not null default 'electrician';
alter table public.auditoriums add column if not exists approval_3_role text not null default 'principal';
alter table public.auditoriums add column if not exists is_locked boolean not null default false;

alter table public.requests add column if not exists requester_id text not null default 'public';
alter table public.requests add column if not exists end_date date not null default current_date;
alter table public.requests add column if not exists duration text not null default '1 day';
alter table public.requests drop constraint if exists requests_duration_check;
alter table public.requests add constraint requests_duration_check check (duration in ('1 day', '2 days', 'multiple days'));
alter table public.requests drop constraint if exists requests_status_check;
update public.requests set status = 'first_approved' where status = 'head_approved';
update public.requests set status = 'second_approved' where status in ('electrician_approved', 'principal_approved', 'maintenance_approved');
alter table public.requests add constraint requests_status_check check (status in ('pending', 'first_approved', 'second_approved', 'approved', 'rejected'));

alter table public.requests enable row level security;

create index if not exists requests_date_idx on public.requests (date);
create index if not exists requests_status_idx on public.requests (status);

notify pgrst, 'reload schema';