create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  department text not null,
  program text not null,
  student_count integer not null check (student_count > 0),
  date date not null,
  end_date date not null default current_date,
  duration text not null default '1 day' check (duration in ('1 day', '2 days', 'multiple days')),
  start_time time,
  end_time time,
  time_slots jsonb not null default '[]'::jsonb,
  auditorium text not null,
  faculty_name text,
  requester_id text not null default 'public',
  requester_type text not null default 'student' check (requester_type in ('student', 'faculty')),
  requester_enrollment_no text,
  requester_name text,
  requester_branch text,
  requester_mobile text,
  rejection_remarks text,
  status text not null default 'pending' check (status in ('pending', 'first_approved', 'second_approved', 'third_approved', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.auditoriums (
  id bigint generated by default as identity primary key,
  name text not null unique,
  capacity integer not null default 300 check (capacity > 0),
  approval_1_role text not null default 'head',
  approval_2_role text not null default 'electrician',
  approval_3_role text not null default 'principal',
  approval_4_role text not null default 'maintenance',
  is_locked boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  head_user_id text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_accounts (
  id text primary key,
  name text not null,
  department text not null,
  role text not null check (role in ('admin', 'sub_admin', 'admin_officer', 'purchase_officer', 'purchase_clerk', 'chairman', 'department_user', 'head', 'maintenance', 'electrician', 'principal', 'higher_authority')),
  password text not null,
  created_at timestamptz not null default now()
);

alter table public.user_accounts drop constraint if exists user_accounts_role_check;
alter table public.user_accounts add constraint user_accounts_role_check check (role in ('admin', 'sub_admin', 'admin_officer', 'purchase_officer', 'purchase_clerk', 'chairman', 'department_user', 'head', 'maintenance', 'electrician', 'principal', 'higher_authority'));

insert into public.departments (name, head_user_id) values
  ('Computer Engineering', 'hod.computer@svitvasad.ac.in')
on conflict (name) do nothing;

insert into public.auditoriums (name) values
  ('Architecture Auditorium'),
  ('Aeronautical Auditorium'),
  ('Main Auditorium'),
  ('Seminar Auditorium')
on conflict (name) do nothing;

alter table public.auditoriums add column if not exists approval_1_role text not null default 'head';
alter table public.auditoriums add column if not exists capacity integer not null default 300;
alter table public.auditoriums drop constraint if exists auditoriums_capacity_check;
alter table public.auditoriums add constraint auditoriums_capacity_check check (capacity > 0);
alter table public.auditoriums add column if not exists approval_2_role text not null default 'electrician';
alter table public.auditoriums add column if not exists approval_3_role text not null default 'principal';
alter table public.auditoriums add column if not exists approval_4_role text not null default 'maintenance';
alter table public.auditoriums add column if not exists is_locked boolean not null default false;
alter table public.auditoriums add column if not exists principal_user_id text;
alter table public.auditoriums add column if not exists maintenance_user_id text;

alter table public.requests add column if not exists requester_id text not null default 'public';
alter table public.requests add column if not exists rejection_remarks text;
alter table public.requests add column if not exists student_count integer not null default 1;
alter table public.requests drop constraint if exists requests_student_count_check;
alter table public.requests add constraint requests_student_count_check check (student_count > 0);
alter table public.requests add column if not exists end_date date not null default current_date;
alter table public.requests add column if not exists duration text not null default '1 day';
alter table public.requests add column if not exists time_slots jsonb not null default '[]'::jsonb;
alter table public.requests add column if not exists requester_type text not null default 'student';
alter table public.requests add column if not exists requester_enrollment_no text;
alter table public.requests add column if not exists requester_name text;
alter table public.requests add column if not exists requester_branch text;
alter table public.requests add column if not exists requester_mobile text;
alter table public.requests add column if not exists requester_email text;
alter table public.requests drop constraint if exists requests_duration_check;
alter table public.requests add constraint requests_duration_check check (duration in ('1 day', '2 days', 'multiple days'));
alter table public.requests drop constraint if exists requests_status_check;
update public.requests set status = 'first_approved' where status = 'head_approved';
update public.requests set status = 'second_approved' where status in ('electrician_approved', 'principal_approved', 'maintenance_approved');
alter table public.requests add constraint requests_status_check check (status in ('pending', 'first_approved', 'second_approved', 'third_approved', 'approved', 'rejected'));

alter table public.requests enable row level security;

create index if not exists requests_date_idx on public.requests (date);
create index if not exists requests_status_idx on public.requests (status);

create table if not exists public.maintenance_requests (
  id bigint generated by default as identity primary key,
  location text not null,
  category text not null check (category in ('electrical', 'plumbing', 'furniture', 'ac_fan', 'carpentry', 'painting', 'civil', 'cleaning', 'other')),
  description text not null,
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high', 'urgent')),
  reporter_name text not null,
  department text not null,
  reporter_mobile text not null,
  reporter_email text not null,
  status text not null default 'pending' check (status in ('pending', 'hod_approved', 'electrician_approved', 'principal_approved', 'maintenance_approved', 'completed', 'rejected')),
  rejection_remarks text,
  assigned_to text,
  remarks text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.maintenance_requests enable row level security;

create index if not exists maintenance_requests_status_idx on public.maintenance_requests (status);
create index if not exists maintenance_requests_priority_idx on public.maintenance_requests (priority);
create index if not exists maintenance_requests_category_idx on public.maintenance_requests (category);

alter table public.maintenance_requests drop constraint if exists maintenance_requests_status_check;
alter table public.maintenance_requests add constraint maintenance_requests_status_check check (status in ('pending', 'hod_approved', 'electrician_approved', 'principal_approved', 'maintenance_approved', 'completed', 'rejected'));
alter table public.maintenance_requests add column if not exists rejection_remarks text;

create table if not exists public.purchase_requests (
  id bigint generated by default as identity primary key,
  purchase_type text not null check (purchase_type in ('local', 'stationary', 'cleaning', 'electric')),
  department text not null,
  item_name text not null,
  item_details jsonb not null default '[]'::jsonb,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null default 0,
  description text not null default '',
  vendor text not null default '',
  requester_name text not null,
  requester_mobile text not null,
  requester_email text not null,
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high', 'urgent')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  rejection_remarks text,
  created_at timestamptz not null default now()
);

alter table public.purchase_requests enable row level security;

create index if not exists purchase_requests_status_idx on public.purchase_requests (status);
create index if not exists purchase_requests_type_idx on public.purchase_requests (purchase_type);

create table if not exists public.car_requests (
  id bigint generated by default as identity primary key,
  department text not null,
  purpose text not null,
  travel_date date not null,
  passenger_count integer not null check (passenger_count > 0),
  passenger_details jsonb not null default '[]'::jsonb,
  pickup_location text not null,
  destination text not null,
  pickup_time time not null,
  return_time time,
  faculty_name text not null default '',
  requester_name text not null,
  requester_mobile text not null,
  requester_email text not null,
  remarks text not null default '',
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  rejection_remarks text,
  created_at timestamptz not null default now()
);

alter table public.car_requests add column if not exists faculty_name text not null default '';
alter table public.car_requests add column if not exists passenger_details jsonb not null default '[]'::jsonb;
alter table public.purchase_requests add column if not exists item_details jsonb not null default '[]'::jsonb;

create table if not exists public.purchase_stock (
  id bigint generated by default as identity primary key,
  category text not null default 'misc' check (category in ('stationary', 'cleaning', 'electric', 'plumbing', 'misc')),
  department text not null,
  item_name text not null,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  updated_at timestamptz not null default now(),
  unique (department, item_name)
);
alter table public.purchase_stock add column if not exists category text not null default 'misc';
alter table public.purchase_stock drop constraint if exists purchase_stock_category_check;
alter table public.purchase_stock add constraint purchase_stock_category_check check (category in ('stationary', 'cleaning', 'electric', 'plumbing', 'misc'));
alter table public.purchase_stock enable row level security;

drop policy if exists "Allow read access to purchase_stock" on public.purchase_stock;
drop policy if exists "Allow insert for purchase officers" on public.purchase_stock;
drop policy if exists "Allow update for purchase officers" on public.purchase_stock;
create policy "Allow read access to purchase_stock" on public.purchase_stock for select using (true);
create policy "Allow insert for purchase officers" on public.purchase_stock for insert with check (true);
create policy "Allow update for purchase officers" on public.purchase_stock for update using (true);

alter table public.car_requests enable row level security;
create index if not exists car_requests_status_idx on public.car_requests (status);
create index if not exists car_requests_travel_date_idx on public.car_requests (travel_date);

notify pgrst, 'reload schema';